[mypy]
plugins = "numpy.typing.mypy_plugin"
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "scm.*",
    "pandas.*",
    "h5py.*",
]
ignore_missing_imports = true
