# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        name: ${{ matrix.os }} (py ${{ matrix.python-version }}${{ matrix.special }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: False
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
                special: ['']
                include:
                    -   os: ubuntu-latest
                        special: '; pre-release'
                        python-version: "3.10"
                    -   os: ubuntu-latest
                        special: '; no-optional'
                        python-version: "3.10"

        steps:
            -   name: Cancel Previous Runs
                uses: styfle/cancel-workflow-action@0.9.1
                with:
                    access_token: ${{ github.token }}

            -   uses: actions/checkout@v2

            -   name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install dependencies
                shell: bash
                run: |
                    case "${{ matrix.special }}" in
                        '; no-optional')
                            pip install -e .[test_no_optional] ;;
                        '; pre-release')
                            pip install --pre -e .[test] --upgrade --force-reinstall ;;
                        *)
                            pip install -e .[test] ;;
                    esac

            -   name: Python info
                run: |
                    which python
                    python --version

            -   name: Installed packages
                run: pip list

            -   name: Test with pytest
                shell: bash
                run: |
                    case "${{ matrix.special }}" in
                        '; no-optional')
                            pytest --mypy ;;
                        *)
                            pytest --doctest-modules --mypy ;;
                    esac

            -   name: Run codecov
                uses: codecov/codecov-action@v2
                with:
                    file: ./coverage.xml
                    name: codecov-umbrella

    Linting:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Python 3.10 on ubuntu-latest
                uses: actions/setup-python@v2
                with:
                    python-version: "3.10"

            -   name: Install linters
                run: pip install flake8 pydocstyle

            -   name: Python info
                run: |
                    which python
                    python --version

            -   name: Installed packages
                run: pip list

            -   name: Run flake8
                run: flake8 docs assertionlib tests
                continue-on-error: true

            -   name: Run pydocstyle
                run: pydocstyle docs assertionlib tests
                continue-on-error: true
