# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.6, 3.7, 3.8]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
              uses: actions/setup-python@v1
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                pip install -e .[test]
                pip install git+https://github.com/numpy/numpy-stubs@master

            - name: Python info
              run: |
                which python
                python --version

            - name: Installed packages
              run: pip list

            - name: Test with pytest
              run: pytest

            - name: Run codecov
              uses: codecov/codecov-action@v1
              with:
                file: ./coverage.xml
                name: codecov-umbrella
