# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: False
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.6, 3.7, 3.8, '3.9.0-alpha - 3.9']

        steps:
            -   name: Cancel Previous Runs
                uses: styfle/cancel-workflow-action@0.9.0
                with:
                    access_token: ${{ github.token }}

            -   uses: actions/checkout@v2

            -   name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install wheel
                if: matrix.python-version == '3.9.0-alpha - 3.9'
                run: pip install wheel

            -   name: Install dependencies
                run: pip install -e .[test]

            -   name: Python info
                run: |
                    which python
                    python --version

            -   name: Installed packages
                run: pip list

            -   name: Test with pytest
                run: pytest

            -   name: Run codecov
                uses: codecov/codecov-action@v1
                with:
                    file: ./coverage.xml
                    name: codecov-umbrella
